---
if: branch = master OR type = pull_request
language: ruby
cache: bundler
rvm:
  - 2.5.3
services:
  - docker # for samlocal
before_install:
  - bin/setup
jobs:
  include:
    - stage: test
      name: Units
    - stage: test
      name: Integration
      before_install:
        - source bin/cibuild
        - bin/bootstrap
        - bin/setup
      script: bin/test integration
script: bin/test
